Rewrite Submit#contest_solutions (contest ranking) logic
zmora-agh/zmora-server-rails pull request #66
Opened 2017-09-20 19:00 UTC by marcmos

Closes #20, #43.

2017-09-21 06:39 UTC, marcmos commented
Przy wrzucaniu zrobić squash.

2017-09-21 18:15 UTC, mflis requested changes

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +    context('contest without solutions') do
lepiej się czyta output jeśli jest słówko  `when` na początku  http://www.betterspecs.org/#contexts

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +        create(:submit, contest_problem: contest_problem)
w jaki sposób ten submit jest spięty z `participant`?
Czy factory nie podłoży pod `author` randomowego usera?

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +      it {
tutaj lepiej dołożyć słowny opis do `it`, bo coś takiego jest mało zrozumiałe na pierwszy rzut oka
```
problem without a valid solution
      should eq [{:user=>#<User id: 2339, nick: "nick37", password_digest: "$2a$04$InobQBY7enhdIx1ecPDMUOWmzF.ZfQ22Em...dmin: false, created_at: "2017-09-21 16:46:03", updated_at: "2017-09-21 16:46:03">, :solutions=>[]}]
```

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +      it do
to samo co przy `problem without a valid solution`

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +      expect(contest_solutions).to have_exactly(1).item
Expect'y pomieszane z setup-em nie wyglądają legitnie wg mnie. W sumie pierwsza połowa testu  jest praktycznie  taka sama w teście wyżej, więc tą cześć zachowania już sprawdziłeś. W związku z tym expecty po pierwszym `create` są wg mnie zbędne

2017-09-21 18:15 UTC, mflis commented on spec/models/submit_spec.rb
> +      expect(contest_solutions).to have_exactly(1).item
jw

2017-09-21 18:17 UTC, mflis commented
Review testowanej metody  zostawiam @maxmati

2017-09-22 11:10 UTC, marcmos commented
@mflis wprowadziłem zmiany.

2017-09-24 18:33 UTC, maxmati approved these changes

2017-09-24 20:07 UTC, mflis approved these changes

2017-09-24 20:13 UTC, merged